web:
  extends:
    file: web.yml
    service: web
  links:
    - db
  environment:
    - DATABASE_URL=postgres://postgres@db:5432/budgie_backend
data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - ~/Library/Application\ Support/Postgres/var-9.5-lol/
db:
  build: ./db/
  volumes_from:
    - data
